{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    p3x-onenote
    teamtype
    blueman
    mangohud
    # superTuxKart
    vpcs
    legendary-gl
    heroic
    qemu
    firefox
    kdePackages.kate
    librewolf
    signal-desktop
    protonup-qt
    # gimp
    thunderbird
    libreoffice-qt
    hollywood
    cbonsai
    cmatrix
    kdePackages.dolphin
    obsidian
    osu-lazer-bin
    protonplus
    stlink-tool
    stlink
    prismlauncher
    keepassxc
    krita
    openconnect
    subversionClient
    asciinema
    zathura
    mumble
    vesktop
    qbittorrent-enhanced
    vlc
    scrcpy
    blahaj
    krita
    lutris
    geckodriver
    gnome-disk-utility
    nautilus
    godot_4
    gurk-rs
  ];
}
